[workspace]
resolver = "3"
members = ["algorithms", "linesonmaps", "segment_experiment","data", "solomon", "tilerizer", "modeling", "fafo", "ferruginous", "etl"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
debug = 0

[workspace.lints.clippy]
# some lint suggestions are from here: https://rust-trends.com/posts/mastering-clippy-elevating-your-rust-code-quality/
# all = { level = "deny", priority = 1 }
complexity = {level = "deny", priority = 1}
correctness = {level = "deny", priority = 1}
perf = {level = "deny", priority = 1}
unwrap_used= {level = "deny", priority = 1}
map_unwrap_or = {level = "deny", priority = 2}
needless_late_init = { level = "deny", priority = 2}

# The following lints are not related to performance/correctness
suspicious = "warn"
todo = "warn"

[workspace.dependencies]
linesonmaps = { path = "linesonmaps" }
data = { path = "data" }
chrono = { version = "0.4.41", features = ["serde"] }
geo-types = { version = "0.7.17" }
modeling = { path = "modeling" }
pgrx = "=0.16.1"
tilerizer = { path = "tilerizer" }
serde = "1.0.228"
rayon = "1.11.0"
duckdb = { version = "1.10503.0", features = ["bundled", "modern-full", "r2d2"]}
rust_decimal = "1.40.0"
clap = { version = "4.5.60", features = ["derive"] }
thiserror = "2.0.18"
nalgebra = "0.34.1"
geo = "0.31.0"
itertools = "0.14.0"
fafo = { path = "fafo" }
algorithms = { path = "algorithms" }
cached = {version = "1.1.0", features = ["time_stores", "ahash"] }
approx = "0.5.1"
wkb = "0.9.2"
r2d2 = "0.8.10"
rstar = "0.12.2"
geo-traits = "0.3.0"
